apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: 182399717212.dkr.ecr.us-east-1.amazonaws.com/producer #ibrahimjamil/producer:latest
