apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - name: subscriber
          image: 182399717212.dkr.ecr.us-east-1.amazonaws.com/subscriber #ibrahimjamil/subscriber:latest
